[Options]
activate_closes=true
activate_focuses=true
activate_item_with_single_click=true
activate_pastes=true
always_on_top=true
close_on_unfocus=true
close_on_unfocus_delay_ms=250
confirm_exit=false
frameless_window=true
hide_main_window=true
hide_main_window_in_task_bar=true
hide_tabs=true
hide_toolbar=true
maxitems=40
open_windows_on_current_screen=true
tabs=&clipboard

[Theme]
alt_bg=#45475A
alt_item_css="\n    ;background: #1E1E2E;"
bg=#1E1E2E
edit_bg=#313244
edit_fg=#CDD6F4
fg=#CDD6F4
find_bg=#CBA6F7
find_fg=#1E1E2E
font="font-family: 'JetBrainsMono NF'; font-size: 10pt;"
hover_item_css="\n    ;background: #585B70;\n    ;border-radius: 4px;"
item_css="\n    ;padding: 10px 14px;\n    ;border-bottom: 1px solid #313244;"
menu_bar_css="\n    ;height: 0px;\n    ;max-height: 0px;\n    ;min-height: 0px;\n    ;border: 0px;\n    ;padding: 0px;\n    ;margin: 0px;"
menu_bar_disabled_css="\n    ;color: #181825"
notes_bg=#181825
notes_fg=#CDD6F4
notification_bg=#313244
notification_fg=#CDD6F4
num_fg=#6C7086
num_sel_fg=#CDD6F4
search_bar="\n    ;background: #313244;\n    ;color: #CDD6F4;\n    ;border: 1px solid #313244;\n    ;border-radius: 6px;\n    ;padding: 6px 12px;\n    ;margin: 8px 10px;\n    ;font-family: 'JetBrainsMono NF';\n    ;font-size: 10pt;"
search_bar_focused="\n    ;border: 1px solid #CBA6F7;"
sel_bg=#313244
sel_fg=#CDD6F4
sel_item_css="\n    ;background: #313244;\n    ;border-left: 3px solid #CBA6F7;"
style_main_window=true
tab_bar_css="\n    ;background: #181825"
tab_bar_item_counter="\n    ;color: #CBA6F7"
tab_bar_scroll_buttons_css="\n    ;background: #181825"
tab_bar_sel_item_counter="\n    ;color: #CBA6F7"
tab_bar_tab_unselected_css="\n    ;background: #181825"
tab_tree_item_counter="\n    ;color: #CBA6F7"
tab_tree_sel_item_counter="\n    ;color: #CBA6F7"
tool_button_selected_css="\n    ;background: #1E1E2E"
